name: "projeto-ii"
services:
  # TODO: Petunia
  mongodb:
    image: mongo:8.2.6-rc0
    restart: always
    ports:
      - "8081:8081"
    volumes:
    - './.data:/data/db'
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 1234Pass
