name: "projeto-ii"
services:
  mysql:
    image: mysql:9.6.0
    restart: always
    ports:
      - "${DB_PORT}:3306"
    volumes:
    - './.data/mysql:/var/lib/mysql'
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
